import { Tool } from '../types';
import {
  MergeIcon,
  SplitIcon,
  CompressIcon,
  PdfToWordIcon,
  PdfToPowerpointIcon,
  PdfToExcelIcon,
  WordToPdfIcon,
  PowerpointToPdfIcon,
  ExcelToPdfIcon,
  EditPdfIcon,
  PdfToJpgIcon,
  JpgToPdfIcon,
  SignPdfIcon,
  WatermarkIcon,
  RotatePdfIcon,
} from './icons';

export const TOOLS: Tool[] = [
  {
    id: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    Icon: MergeIcon,
    path: '/merge-pdf',
    color: 'bg-brand-red/10 text-brand-red',
    hoverColor: 'hover:bg-brand-red/20',
    accept: 'application/pdf',
    outputFilename: 'merged.pdf',
  },
  {
    id: 'split-pdf',
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    Icon: SplitIcon,
    path: '/split-pdf',
    color: 'bg-brand-red/10 text-brand-red',
    hoverColor: 'hover:bg-brand-red/20',
    accept: 'application/pdf',
    outputFilename: 'split.pdf',
  },
  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF quality.',
    Icon: CompressIcon,
    path: '/compress-pdf',
    color: 'bg-brand-red/10 text-brand-red',
    hoverColor: 'hover:bg-brand-red/20',
    accept: 'application/pdf',
    outputFilename: 'compressed.pdf',
  },
  {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Easily convert your PDF files into easy to edit DOC and DOCX documents.',
    Icon: PdfToWordIcon,
    path: '/pdf-to-word',
    color: 'bg-medium-gray/10 text-medium-gray',
    hoverColor: 'hover:bg-medium-gray/20',
    accept: 'application/pdf',
    outputFilename: 'converted.docx',
  },
  {
    id: 'pdf-to-powerpoint',
    title: 'PDF to PowerPoint',
    description: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
    Icon: PdfToPowerpointIcon,
    path: '/pdf-to-powerpoint',
    color: 'bg-medium-gray/10 text-medium-gray',
    hoverColor: 'hover:bg-medium-gray/20',
    accept: 'application/pdf',
    outputFilename: 'converted.pptx',
  },
  {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Pull data straight from PDFs into Excel spreadsheets in a few short clicks.',
    Icon: PdfToExcelIcon,
    path: '/pdf-to-excel',
    color: 'bg-medium-gray/10 text-medium-gray',
    hoverColor: 'hover:bg-medium-gray/20',
    accept: 'application/pdf',
    outputFilename: 'converted.xlsx',
  },
  {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    Icon: WordToPdfIcon,
    path: '/word-to-pdf',
    color: 'bg-medium-gray/10 text-medium-gray',
    hoverColor: 'hover:bg-medium-gray/20',
    accept: '.doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    outputFilename: 'converted.pdf',
  },
  {
    id: 'powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    description: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
    Icon: PowerpointToPdfIcon,
    path: '/powerpoint-to-pdf',
    color: 'bg-medium-gray/10 text-medium-gray',
    hoverColor: 'hover:bg-medium-gray/20',
    accept: '.ppt,.pptx,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation',
    outputFilename: 'converted.pdf',
  },
  {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Make EXCEL spreadsheets easy to read by converting them to PDF.',
    Icon: ExcelToPdfIcon,
    path: '/excel-to-pdf',
    color: 'bg-medium-gray/10 text-medium-gray',
    hoverColor: 'hover:bg-medium-gray/20',
    accept: '.xls,.xlsx,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    outputFilename: 'converted.pdf',
  },
  {
    id: 'edit-pdf',
    title: 'Edit PDF',
    description: 'Add text, images, shapes or freehand annotations to a PDF document.',
    Icon: EditPdfIcon,
    path: '/edit-pdf',
    color: 'bg-brand-red/10 text-brand-red',
    hoverColor: 'hover:bg-brand-red/20',
    accept: 'application/pdf',
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG or extract all images contained in a PDF.',
    Icon: PdfToJpgIcon,
    path: '/pdf-to-jpg',
    color: 'bg-medium-gray/10 text-medium-gray',
    hoverColor: 'hover:bg-medium-gray/20',
    accept: 'application/pdf',
    outputFilename: 'images.zip',
  },
  {
    id: 'jpg-to-pdf',
    title: 'JPG to PDF',
    description: 'Convert JPG images to PDF in seconds. Easily adjust orientation and margins.',
    Icon: JpgToPdfIcon,
    path: '/jpg-to-pdf',
    color: 'bg-medium-gray/10 text-medium-gray',
    hoverColor: 'hover:bg-medium-gray/20',
    accept: 'image/jpeg,image/png',
    outputFilename: 'converted.pdf',
  },
  {
    id: 'sign-pdf',
    title: 'Sign PDF',
    description: 'Sign yourself or send signature requests to others. No need to print!',
    Icon: SignPdfIcon,
    path: '/sign-pdf',
    color: 'bg-brand-red/10 text-brand-red',
    hoverColor: 'hover:bg-brand-red/20',
    accept: 'application/pdf',
  },
  {
    id: 'watermark',
    title: 'Watermark',
    description: 'Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.',
    Icon: WatermarkIcon,
    path: '/watermark',
    color: 'bg-brand-red/10 text-brand-red',
    hoverColor: 'hover:bg-brand-red/20',
    accept: 'application/pdf',
  },
  {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!',
    Icon: RotatePdfIcon,
    path: '/rotate-pdf',
    color: 'bg-brand-red/10 text-brand-red',
    hoverColor: 'hover:bg-brand-red/20',
    accept: 'application/pdf',
    outputFilename: 'rotated.pdf',
  },
];